### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by p00h** [creatoro/jelly-auth#4]
Hello!
I've found an issue while digging into code.

file:
_classes/kohana/auth/jelly.php at line 76_
<code>if ($user->has('roles', Jelly::factory('role')->get_role('login')) AND $user->password === $password)</code>
hashed password loaded from DB (<code>$user->password</code>) comparing with unhashed password at all (<code>$password</code>) so login will never happen.

**Comment by creatoro** [comment]
@p00h: it would be only a problem if the password wouldn't be hashed by Kohana's Auth module before passing the password to this method. Check this out: https://github.com/kohana/auth/blob/3.1/master/classes/kohana/auth.php#L93

The 3.2 branch is different in this matter as the hashing was removed from the Auth module and is done by the drivers:
https://github.com/creatoro/jelly-auth/blob/3.2/develop/classes/kohana/auth/jelly.php#L70

**Comment by p00h** [comment]
Oh... Where am i watching? Sorry plz for issue, closing it.
